#!/usr/bin/env node

/**
 * Build script to convert markdown blog posts to JavaScript
 * This generates blog-posts.js which is loaded by blog.html
 */

const fs = require('fs');
const path = require('path');
const { marked } = require('marked');

const POSTS_DIR = path.join(__dirname, '_posts');
const OUTPUT_FILE = path.join(__dirname, 'blog-posts.js');

// Configure marked for safer HTML output
marked.setOptions({
  headerIds: false,
  mangle: false
});

function parseFrontMatter(content) {
  const frontMatterRegex = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/;
  const match = content.match(frontMatterRegex);

  if (!match) {
    throw new Error('No front matter found');
  }

  const frontMatter = {};
  const lines = match[1].split('\n');

  lines.forEach(line => {
    const colonIndex = line.indexOf(':');
    if (colonIndex === -1) return;

    const key = line.substring(0, colonIndex).trim();
    let value = line.substring(colonIndex + 1).trim();

    // Remove quotes if present
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    frontMatter[key] = value;
  });

  const body = match[2];

  return { frontMatter, body };
}

function readPosts() {
  if (!fs.existsSync(POSTS_DIR)) {
    console.warn('No _posts directory found. Creating empty posts array.');
    return [];
  }

  const files = fs.readdirSync(POSTS_DIR)
    .filter(file => file.endsWith('.md'))
    .sort()
    .reverse(); // Most recent first

  const posts = [];

  for (const file of files) {
    try {
      const filePath = path.join(POSTS_DIR, file);
      const content = fs.readFileSync(filePath, 'utf8');
      const { frontMatter, body } = parseFrontMatter(content);

      // Convert markdown to HTML
      const htmlContent = marked.parse(body);

      posts.push({
        slug: frontMatter.slug || file.replace('.md', ''),
        title: frontMatter.title || 'Untitled',
        date: frontMatter.date || '',
        content: htmlContent.trim()
      });
    } catch (error) {
      console.error(`Error processing ${file}:`, error.message);
    }
  }

  return posts;
}

function generateJavaScript(posts) {
  const postsJson = JSON.stringify(posts, null, 2);

  return `// Auto-generated by build-posts.js
// Do not edit this file manually - edit markdown files in _posts/ instead

const posts = ${postsJson};
`;
}

function main() {
  console.log('Building blog posts...');

  const posts = readPosts();
  const jsContent = generateJavaScript(posts);

  fs.writeFileSync(OUTPUT_FILE, jsContent, 'utf8');

  console.log(`✓ Generated ${OUTPUT_FILE} with ${posts.length} post(s)`);
  posts.forEach(post => {
    console.log(`  - ${post.date} - ${post.title}`);
  });
}

main();
